# Generated by Django 4.1 on 2022-09-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_uploadimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimg',
            name='name',
            field=models.CharField(default=1234, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadimg',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
