# Generated by Django 4.1 on 2022-09-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_uploadimg_name_alter_uploadimg_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uploadimg',
        ),
    ]
