# Generated by Django 4.1 on 2022-09-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_uploadimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
