# Generated by Django 4.1 on 2022-09-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.AddField(
            model_name='signup',
            name='otp',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
