# Generated by Django 4.1 on 2022-10-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_signup_service_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_service',
            name='id',
        ),
        migrations.AddField(
            model_name='signup_service',
            name='uid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup_service',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
