# Generated by Django 4.1 on 2022-10-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_signup_service_id_signup_service_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_service',
            name='uid',
        ),
        migrations.AddField(
            model_name='signup_service',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
