# Generated by Django 4.1 on 2022-10-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_signup_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_service',
            name='token',
            field=models.CharField(default=1, max_length=22),
            preserve_default=False,
        ),
    ]
