# Generated by Django 4.1 on 2022-10-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_signup_service_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='perfect_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt_offered', models.IntegerField()),
                ('customer_usr', models.CharField(max_length=50)),
                ('service_usr', models.CharField(max_length=50)),
                ('service_boolean', models.BooleanField()),
            ],
        ),
    ]
