# Generated by Django 4.1 on 2022-10-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_perfect_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfect_service',
            name='service_boolean',
            field=models.BooleanField(default=False),
        ),
    ]
