# Generated by Django 4.1 on 2022-10-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_perfect_service_service_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfect_service',
            name='service_boolean',
            field=models.CharField(max_length=5),
        ),
    ]
