# Generated by Django 4.1 on 2022-10-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_perfect_service_service_boolean'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfect_service',
            name='customer_boolean',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfect_service',
            name='ser_amt_offered',
            field=models.CharField(default='NOT SEEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfect_service',
            name='service_boolean',
            field=models.CharField(max_length=1),
        ),
    ]
