# Generated by Django 4.1 on 2022-10-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_perfect_service_customer_boolean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfect_service',
            name='final',
            field=models.IntegerField(default=0),
        ),
    ]
