# Generated by Django 4.1 on 2022-10-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_perfect_service_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfect_service',
            name='service_recieved',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
