# Generated by Django 4.1 on 2022-10-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_perfect_service_service_recieved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfect_service',
            name='service_recieved',
        ),
    ]
