# Generated by Django 4.1 on 2022-10-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_perfect_service_service_recieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfect_service',
            name='service',
            field=models.CharField(default='barber', max_length=50),
        ),
    ]
