# Generated by Django 4.1 on 2022-10-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_perfect_service_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfect_service',
            name='service',
            field=models.CharField(default='NONE', max_length=50),
        ),
    ]
